FROM mcr.microsoft.com/dotnet/sdk:3.1.404-buster-arm32v7 AS build-env

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:3.1.10-buster-slim-arm32v7

WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

# Expose the port
EXPOSE 5013

ENTRYPOINT ["dotnet", "ImageProcessorModule.dll"]