FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7 AS build-env
ENV PATH="/opt/vc/bin:${PATH}"
ENV LD_LIBRARY_PATH="/opt/vc/lib:${LD_LIBRARY_PATH}"
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "DeviceCheckModule.dll"]